config/routes.rb
Rails.application.routes.draw do
  resources :searches, only:[:show,:new,:create]

  devise_for :users , :path => 'accounts'
  resources :books do
    member do
        post :appoint
        post :add_copy
    end
  end

  resources :publishers
  resources :authors
  namespace :librarian do
    resources :bills
    resources :receipts
  end
  namespace :admin do
    resources :users
  end
  resources :users do
    resources :bills
    resources :receipts
  end 
  root 'home#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
    has_many :booksAuthors
    has_many :books, through: :booksAuthors
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    load_and_authorize_resource
    def show
#        @author = Author.find params[:id]
        @books = @author.books
    end

    def edit
#        @author = Author.find params[:id]
    end

    def update
        @author = Author.find params[:id]
            if @author.update( author_params )
                redirect_to author_url(@author)
            else
                render :action => :edit
            end
    end

    protected
    def author_params
        params.require(:author).permit(:name,:organization)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<tr>
    <td> <%= link_to author.name, author_url(author) %> </td>
    <% if author.organization %>
        <td> <%= author.organization %> </td>
    <% else %>
        <td> #### </td>
    <% end %>
</tr>

app/views/authors/edit.html.erb
<h1> 修改作者資料  </h1>
<%= simple_form_for @author do |f| %>
    <%= f.input :name %>
    <%= f.input :organization %>
    <%= f.button :submit %>
<% end %>

app/views/authors/show.html.erb
<h1> 作者介紹 </h1>
<% if can? :update, Author %>
    <%= button_to "修改作者資料", edit_author_url(@author), {method: :get , class:"btn btn-default"}%>
<% end %>
<h3>資料</h3>
<table class="table">
    <thead>
        <tr>
            <th>姓名</th>
            <th>所屬組織</th>
        </tr>
    </thead>
    <tbody>
        <%= render @author %>
    </tbody>
</table>
<h3>擁有的書</h3>
<table class="table">
    <thead>
        <tr>
            <th>標題</th>
            <th>ISBN</th>
            <th>出版日期</th>
            <th>副本數</th>
            <th>分類</th>
        </tr>
    </thead>
    <tbody>
        <%= render @books %>
    </tbody>
</table>