config/routes.rb
Rails.application.routes.draw do
  resources :searches, only:[:show,:new,:create]

  devise_for :users , :path => 'accounts'
  resources :books do
    member do
        post :appoint
        post :add_copy
    end
  end

  resources :publishers
  resources :authors
  namespace :librarian do
    resources :bills
    resources :receipts
  end
  namespace :admin do
    resources :users
  end
  resources :users do
    resources :bills
    resources :receipts
  end 
  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

#    if params[:keyword]
#        @books = Book.where( [ "title like ?", "%#{params[:keyword]}%" ] )
#    end
    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
    <h1> 線上圖書館系統 </h1>
    <p>使用說明請參考規格書。</p>
    <%= button_to "開始使用", books_url , {method: :get, class: "btn btn-primary"}%>
</div>

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            <a data-toggle="collapse" href="#collapse1"><h4 class="panel-title">
               組員名單</h4></a>
 
        </div>
        <div id="collapse1" class="panel-collapse collapse">
            <ul class="list-group">
                <li class="list-group-item list-group-item-success">王祥益</li>
                <li class="list-group-item list-group-item-info">鄭淳丰</li>
                <li class="list-group-item list-group-item-warning">黃柏瑋</li>
                <li class="list-group-item list-group-item-info">詹智德</li>
                <li class="list-group-item list-group-item-success">傅意茹</li>
            </ul>
        </div>
    </div>
</div>