config/routes.rb
Rails.application.routes.draw do
  resources :searches, only:[:show,:new,:create]

  devise_for :users , :path => 'accounts'
  resources :books do
    member do
        post :appoint
        post :add_copy
    end
  end

  resources :publishers
  resources :authors
  namespace :librarian do
    resources :bills
    resources :receipts
  end
  namespace :admin do
    resources :users
  end
  resources :users do
    resources :bills
    resources :receipts
  end 
  root 'home#index'

end

app/models/search.rb
class Search < ActiveRecord::Base

def books
  @books ||= find_books
end
def find_books
#Book.joins(:authors).joins(:publisher).where(conditions)
    unless authors.blank?
        authors_cond
    else
        Book.eager_load(:authors).eager_load(:publisher).where(conditions)
    end       
end

private

def parse_authors
    arr = authors.split(';')
    [arr,arr.size]
end

def author_cond(name)
    ["authors.name = ?",name]
end


def keyword_conditions
  ["books.title LIKE ?", "%#{keyword}%"] unless keyword.blank?
end

def authors_cond
    authors,num = parse_authors
    Book.eager_load(:authors).eager_load(:publisher).where(conditions).where('authors.name IN (?)',authors).group('books.id').having('COUNT(DISTINCT authors.id) >= ?',num)
end

def publisher_conditions
  ["publishers.id = ?", publisher_id] unless publisher_id.blank?
end

def conditions
  [conditions_clauses.join(' AND '), *conditions_options]
end

def conditions_clauses
  conditions_parts.map { |condition| condition.first }
end

def conditions_options
  conditions_parts.map { |condition| condition[1..-1] }.flatten
end

def conditions_parts
  private_methods(false).grep(/_conditions$/).map { |m| send(m) }.compact
end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show]

  # GET /searches/1
  # GET /searches/1.json
  def show
    @books = @search.find_books
  end

  # GET /searches/new
  def new
    @search = Search.new
  end


  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:keyword, :authors, :publisher_id)
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<%= simple_form_for(@search) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :keyword %>
    <%= f.input :authors , placeholder:"用分號隔開"%>
    <%= f.input :publisher_id, collection: Publisher.all%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Searches</h1>

<table>
  <thead>
    <tr>
      <th>Keyword</th>
      <th>Authors</th>
      <th>Publisher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.keyword %></td>
        <td><%= search.authors %></td>
        <td><%= search.publisher_id %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>進階搜尋</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/searches/show.html.erb
<%= link_to '新搜尋', new_search_url %>

<table>

<%= render @books %>

</table>