config/routes.rb
Rails.application.routes.draw do
  resources :searches, only:[:show,:new,:create]

  devise_for :users , :path => 'accounts'
  resources :books do
    member do
        post :appoint
        post :add_copy
    end
  end

  resources :publishers
  resources :authors
  namespace :librarian do
    resources :bills
    resources :receipts
  end
  namespace :admin do
    resources :users
  end
  resources :users do
    resources :bills
    resources :receipts
  end 
  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :add_reader
  has_many :receipts
  has_many :bills
  has_many :copies, through: :receipts
  protected
  def add_reader
    self.add_role(:reader) if self.roles.blank?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
    load_and_authorize_resource

    def index
#        @users = User.all
    end

    def new
#        @user = User.new
    end

    def create
#        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Successfully created User." 
            redirect_to admin_users_path
        else
            render :action => 'new'
        end
    end

    def edit
#        @user = User.find(params[:id])
    end

    def update
#        @user = User.find(params[:id])
        params[:user].delete(:password) if params[:user][:password].blank?
        params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
        if @user.update_attributes(user_params)
            flash[:notice] = "Successfully updated User."
            redirect_to admin_users_url
        else
            render :action => 'edit'
        end
    end

    def destroy
#        @user = User.find(params[:id])
        if @user.destroy
            flash[:notice] = "Successfully deleted User."
            redirect_to admin_users_path
        end
    end
    protected
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    load_and_authorize_resource 
    def show
#        @user = current_user
        @bills = current_user.bills
        @receipts = current_user.receipts
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_user.html.erb
<tr>
    <td> <%= user.email %></td>
    <td> <%= user.name %></td>
    <td> <%= button_to "修改",edit_admin_user_url(user),{ class: "btn btn-warning", :method => :get} %> </td>
    <td> <%= button_to "刪除",admin_user_url(user), :method => :delete , class: "btn btn-danger"%> </td>
</tr>

app/views/admin/users/edit.html.erb
<h2> 修改讀者資料 </h2>
<%= simple_form_for @user,:url => admin_user_url(@user), :method => :patch do |f| %>
  <%= f.input :email %>
  <%= f.input :name  %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit, class: "btn btn-primary"%>
<% end %>

app/views/admin/users/index.html.erb
<h2> 管理用戶 </h2>
<%= link_to "新增用戶",new_admin_user_url %>
<table class="table">
    <thead>
        <th>email</th>
        <th>名字</th>
    </thead>
    <tbody>
        <%= render @users %>
    </tbody>
</table>

app/views/admin/users/new.html.erb
<h2> 新增讀者 </h2>
<%= simple_form_for @user,:url => admin_users_path do |f| %>
  <%= f.input :email %>
  <%= f.input :name  %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/admin/users/show.html.erb
<h2> show </h2>
<table>
    <%= render @user %>
</table>